version: '3'
tasks:
  install-tools:
    desc: Install necessary tools
    cmds:
      - sudo apt-get install -y apt-transport-https ca-certificates curl
    sudo: true

  disable-swap:
    desc: Disable swap to meet Kubernetes requirements
    cmds:
      - sudo swapoff -a
      - sudo sed -i '/swap/d' /etc/fstab
    sudo: true

  add-kubernetes-repo:
    desc: Add Kubernetes community APT repository and GPG key
    cmds:
      - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      - echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
      - sudo apt-get update
    sudo: true

  install-containerd:
    desc: Install and configure containerd container runtime with IPv4 forwarding
    cmds:
      - sudo apt-get update && sudo apt-get install -y containerd
      - sudo mkdir -p /etc/containerd
      - sudo containerd config default | sudo tee /etc/containerd/config.toml
      - sudo sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
      - sudo sysctl -w net.ipv4.ip_forward=1
      - echo "net.ipv4.ip_forward=1" | sudo tee -a /etc/sysctl.conf
      - sudo sysctl --system
      - sudo modprobe br_netfilter
      - echo "br_netfilter" | sudo tee /etc/modules-load.d/br_netfilter.conf
      - sudo sysctl -w net.bridge.bridge-nf-call-iptables=1
      - echo "net.bridge.bridge-nf-call-iptables=1" | sudo tee -a /etc/sysctl.conf
      - sudo systemctl restart containerd
      - sudo systemctl enable containerd
    sudo: true

  install-kubeadm:
    desc: Install kubeadm, kubelet, and kubectl
    cmds:
      - sudo apt-get update
      - sudo apt-get install -y kubelet kubeadm kubectl
      - sudo apt-mark hold kubelet kubeadm kubectl
    sudo: true

  initialize_kubernetes:
    desc: Initialize kubernetes
    cmds:
      - sudo kubeadm init
    sudo: true

  setup-kubernetes:
    desc: Complete setup for kubeadm on Ubuntu 24.04 using community-owned repositories
    cmds:
      - task: install-tools
      - task: disable-swap
      - task: install-containerd
      - task: add-kubernetes-repo
      - task: install-kubeadm
      - task: initialize_kubernetes